description: OpenR1 Training on Singularity

target:
  service: sing
  name: whitney08
  workspace_name: dca-singularity

environment:
  image: amlt-sing/acpt-rocm6.1_ubuntu20.04_py3.9_pytorch2.1.2
  setup:
    - pwd
    - sudo apt-get update
    - sudo apt-get install -y vim
    - pip install uv
    - uv venv openr1 --python 3.11
    - source openr1/bin/activate
    - uv pip install --upgrade pip setuptools
    - uv pip install packaging wheel ninja
    - uv pip install --upgrade packaging wheel ninja

    - uv pip install vllm==0.7.2
    - uv pip install flash-attn --no-build-isolation
    - GIT_LFS_SKIP_SMUDGE=1 uv pip install -e ".[dev]"
    - uv pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/rocm6.1
    
    - cd /mnt/external
    - nohup python keep.py --gpus=2 >/dev/null 2>&1 &

    - sudo apt-get install git-lfs
    - git-lfs --version
    - git config --global credential.helper store

storage:
  input:
    storage_account_name: dcasingularity4556773921
    container_name: qingtaoli
    mount_dir: /mnt/input
  output:
    storage_account_name: dcasingularity4556773921
    container_name: qingtaoli
    mount_dir: /mnt/output
  external:
    storage_account_name: dcasingularity4556773921
    container_name: qingtaoli
    mount_dir: /mnt/external

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: /home/qingtaoli/BitDistiller/test/3rdparty/open-r1

data:
  storage_id: external


jobs:
- name: new_VC_test_G8
  sku: NDMI300Xv5:G8
  identity: managed
  submit_args:
    env:
      _AZUREML_SINGULARITY_JOB_UAI: "/subscriptions/656a79af-6a27-4924-ad92-9221860e3bba/resourceGroups/dca-core/providers/Microsoft.ManagedIdentity/userAssignedIdentities/dca-core-identity"
  command:
    - nohup python keep.py --gpus=8 >/dev/null 2>&1 &
    - source openr1/bin/activate
    - wandb login 6827e1b8e499d61cb7f1779f3dea534cfaf36c59
    - ACCELERATE_LOG_LEVEL=info accelerate launch --config_file recipes/accelerate_configs/zero2.yaml --num_processes=7 src/open_r1/grpo.py --config recipes/DeepSeek-R1-Distill-Qwen-14B/grpo/config_demo.yaml
    - sleep 100000000
  tags: ["Debug:True"]
  priority: High
  azml_int: True
